config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
    unlocks: 'users/unlocks',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'tweets#index'

  resources :tweets do
    get :following, on: :collection
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/tweet.rb
# frozen_string_literal: true

class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  def display_time
    if created_at > 1.day.ago
      "#{time_ago_in_words(created_at)}前"
    elsif created_at.year == Time.current.year
      created_at.strftime('%-m月%-d日')
    else
      created_at.strftime('%Y年%-m月%-d日')
    end
  end

  def self.followings(current_user)
    following_ids = current_user.followings.pluck(:id)
    Tweet.where(user_id: following_ids).order(created_at: :desc)
  end
end

app/controllers/tweets_controller.rb
# frozen_string_literal: true

class TweetsController < ApplicationController
  def index
    @user = current_user
    @tweets = Tweet.includes(:user)
                   .order(created_at: :desc)
                   .page(params[:page]).per(20)
  end

  def following
    @user = current_user
    @tweets = Tweet.includes(:user)
                   .followings(current_user)
                   .page(params[:page]).per(20)
    render :index
  end
end

app/helpers/tweets_helper.rb
# frozen_string_literal: true

module TweetsHelper
  def display_time(tweet)
    if tweet.created_at > 1.week.ago
      "#{time_ago_in_words(tweet.created_at)}前"
    elsif tweet.created_at.year == Time.current.year
      tweet.created_at.strftime('%-m月%-d日')
    else
      tweet.created_at.strftime('%Y年%-m月%-d日')
    end
  end
end

app/views/tweets/_sidebar.html.slim
aside.a-sidebar
  .a-menu
    ul
      li
        = link_to root_path
          i.fas.fa-home
          span ホーム
      li
        = link_to '#'
          i.fas.fa-hashtag
          span 話題を検索
      li
        = link_to '#'
          i.fas.fa-bell
          span 通知
      li
        = link_to '#'
          i.fas.fa-envelope
          span メッセージ
      li
        = link_to '#'
          i.fas.fa-bookmark
          span ブックマーク
      li
        = link_to '#'
          i.fas.fa-user
          span プロフィール
      li
        = link_to '#'
          i.fas.fa-ellipsis-h
          span もっと見る
  
  - if user
    .a-user-info
      = image_tag(asset_path('default_icon.jpg'), class: "a-user-icon")

      .a-right-block
        .a-primary= user.username
        .a-secondary= "@#{user.user_id}"

app/views/tweets/_tweet_content.html.slim
article
  .a-wrapper
    = image_tag(asset_path('default_icon.jpg'), class: "a-user-icon")

    .a-right-block
      .a-header
        .a-user-info
          .a-info-item.a-name= tweet.user.username
          .a-info-item.a-id= "@#{tweet.user.user_id}"
          .a-info-item.a-time= display_time(tweet)
      .a-content
        p= tweet.content
        - if tweet.image.present?
          = image_tag(tweet.image, class: "a-content-image")
      .a-actions
        .a-icons
          i.fas.fa-comment
          i.fas.fa-retweet
          i.fas.fa-heart
          i.fas.fa-share

app/views/tweets/_tweet_form.html.slim
form
  .a-wrapper
    = image_tag(asset_path('default_icon.jpg'), class: "a-user-icon")

    .a-right-block
      textarea[placeholder="いまどうしてる？"]
  
      .a-actions
        .a-icons
          i.fas.fa-image
        button.btn.btn-primary ツイートする

app/views/tweets/index.html.slim
.container
  .main
    = render 'sidebar', user: current_user

    .content
      - if notice || alert
       = render 'shared/flash'

      - if current_user
        .tabs
          .title ホーム
          ul.nav.nav-tabs
            li.nav-item
              = link_to "おすすめ", tweets_path, class: "nav-link #{'active' if current_page?(tweets_path)}"
            li.nav-item
              = link_to "フォロー中", following_tweets_path, class: "nav-link #{'active' if current_page?(following_tweets_path)}"

        // ツイート投稿部分
        .tweet-form
          = render 'tweet_form'
      
      // ツイート一覧部分
      .tweets
        - @tweets.each do |tweet|
          = render 'tweet_content', tweet: tweet
      
      .paginate
        = paginate(@tweets)